### PR TITLE
#32 - Scope Event Index to events that have not happened yet

### PR DESCRIPTION
**Pull request by exegeteio**
- Added a scope to the Event model to get ongoing or upcoming Events.
- Added spec for testing that only future and ongoing events are selected, while past events are not.
- Updated events controller to select only ongoing or upcoming events.

### CODE REVIEW

**Review by ChaelCodes — COMMENTED** [review]
I love this, but could you add a feature test? And what happens if it ends today? And our events that only take place over an afternoon, like a meetup.

**Comment by exegeteio** [comment]
I was debating adding this to `features/events/index_spec.rb`, but got concerned that the feature testing may become brittle if the definition of `Event#ongoing_or_upcoming` changes.  

As for events which end today, those should get included in the existing query.

As for events with only a few hours, I had not considered how those would be effected.  I can switch to using `Time.zone.now` for the comparison, unless it would better serve the user to include those events which happened today?

**Comment by ChaelCodes** [comment]
> I was debating adding this to `features/events/index_spec.rb`, but got concerned that the feature testing may become brittle if the definition of `Event#ongoing_or_upcoming` changes.  

Would you consider a request spec a better choice? Really, we're just verifying the integration there. It only needs one test though. Just verifying that a past event isn't listed.

> As for events which end today, those should get included in the existing query.

Thanks!

> As for events with only a few hours, I had not considered how those would be effected.  I can switch to using `Time.zone.now` for the comparison, unless it would better serve the user to include those events which happened today?

I think this is good. I can see someone wanting all events that happened today, but that can be an issue when someone wants it.

**Comment by exegeteio** [comment]
Updated with with a feature spec, comparison to the current time when requesting the Events, and (because it's used in multiple specs) a Factory for `:past_event`.  Hopefully a little humor is welcome in the Factories?

**Review by ChaelCodes — APPROVED** [review]
This looks great!!! This'll make the events page a lot cleaner!✨

**Pull request merged**
