### PR TITLE
WIP: #36 Adds Format and Uniqueness Checks to Profile

### LINKED ISSUE #36: Profile's handle is Unique
# Description
We'd like to make the handles on profiles a slug in the URL, so instead of `/profiles/3` the user will see `/profiles/ChaelCodes`. In order to do this, we need to ensure the handle is unique, and url-able. This story is to validate that new profiles have unique handles, regardless of the case. If you could include some common URL checks, like removing '/', '?', and spaces, that'd be great!

# Implementation
A model-level [validation](https://guides.rubyonrails.org/active_record_validations.html#validation-helpers) on Profile that checks for the uniqueness of handle would be great.

### PR DESCRIPTION
**Pull request by yagosansz**
Hi @ChaelCodes,

I've added Format and Uniqueness checks for Profile.

For the Format validation, I assumed for now that only letters should be allowed in the handle, right?

Should I also add tests for those validation checks? 

Closes #36

### CODE REVIEW

**Review by ChaelCodes — APPROVED** [review]
No tests needed, because we'd just be testing Rails functionality.

**Comment by yagosansz** [comment]
Thank you! It was a pretty nice learning experience! I didn't even know what was a slug or handle =)

Is that okay if I look for other open issues to contribute?

**Comment by ChaelCodes** [comment]
> Thank you! It was a pretty nice learning experience! I didn't even know what was a slug or handle =)
> 
> Is that okay if I look for other open issues to contribute?

Of course!! By the way, I didn't have CI running against forked repos, so we didn't catch some spec failures with this PR, but that'll be fixed by tomorrow morning.

**Comment by yagosansz** [comment]
Okay! Let me know if there is anything that needs to be updated and I'll be more than happy to work on it!

**Comment by ChaelCodes** [comment]
> Okay! Let me know if there is anything that needs to be updated and I'll be more than happy to work on it!

So I've created #68 to briefly describe the necessary changes. I decide to add back numbers at this stage to make the sequence easier to setup. If we throw a sequence on the Profile factory, it should fix the build.

**Pull request merged**
