### PR TITLE
#51 - Don't Share Event Attendance with everyone

### PR DESCRIPTION
**Pull request by franciscoFPL**
### Description

issue #51

We want to display in the event index only the event_attendee for the current user, due to privacy policies.

### Changes
- Add authenticate_user! method to the Event Attendees Index Method. 
- Search only for Event Attendees associate with the current_user profile.
- Add auth helper in index test for Event Attendees.

### CODE REVIEW

**Review by ChaelCodes — COMMENTED** [review]
This looks great!! Would you mind adding a test to check that the user can't see event attendees that are not theirs? Basically, just making another event attendees, and checking it's not shown.

**Comment by franciscoFPL** [comment]
> This looks great!! Would you mind adding a test to check that the user can't see event attendees that are not theirs? Basically, just making another event attendees, and checking it's not shown.

Done :smile: 
image

**Review by ChaelCodes — APPROVED** [review]
Thanks!! This looks great!

**Comment by ChaelCodes** [comment]
cute-anime-dancing
> 
> 
Extra love for the Kaguya-sama: Love is War gif!

**Pull request merged**
